#!/usr/bin/env python

# Location: <repository>/.git/hooks/prepare-commit-msg
#
# If a branch name starts with a Pivotal Tracker story
# ID, this script will append a link to that story on
# Pivotal to the commit message.
#
# Example:
#
# 1234567_branch_name => 'commit message https://www.pivotaltracker.com/story/show/1234567'

import sys
import re
import subprocess

commit_msg_path = sys.argv[1]
commit_msg_file = open(commit_msg_path, 'r+')
commit_msg = commit_msg_file.read()

branch_name = subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'])

match = re.search('^\d+(?=_)', branch_name)
if match != None:
    pivotal_id = match.group(0)
    commit_msg_file.write('\nhttps://www.pivotaltracker.com/story/show/' + pivotal_id)

